name: 'Hardhat Test'
description: 'Simple wrapper of hardhat test for GitHub Action'
author: 'ambersun1234'
inputs:
  network:
   description: 'Blockchain network'
   required: true
   default: 'hardhat'
  private_key:
   description: 'Testnet account'
   required: false
  rpc_url:
    description: 'RPC node url'
    required: false

runs:
  using: 'node16'
  main: 'dist/main.js'

branding:
  icon: box
  color: yellow